site_name: APIRequest
repo_url: https://github.com/Rooyca/obsidian-api-request/
edit_uri: edit/master/docs/docs/

markdown_extensions:
  - admonition

theme:
  features:
    - content.code.copy
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - English: 
    - Usage: en/codeblocks.md
    - Use Cases: en/usecase
  - Español:
    - Inicio: es/index.md
    - Uso:
      - Cómo usar: es/codeblocks.md
      - Casos de uso: es/usecase
  - 中文:
    - 概述: zh/index.md
    - 用法: 
        - 代码块: zh/codeblocks.md
        - 用例: zh/usecase
